"""empty message

Revision ID: 53fa2138c8c8
Revises: 633b107703f7
Create Date: 2023-09-13 18:28:40.812759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53fa2138c8c8'
down_revision = '633b107703f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persons_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('planet_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vehicle_name', sa.String(length=50), nullable=True))

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_id', sa.Integer(), nullable=True))
        batch_op.alter_column('persons_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_constraint('people_vehicle_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('people_planet_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'favorites', ['favorites_id'], ['id'])
        batch_op.drop_column('planet_id')
        batch_op.drop_column('vehicle_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('people_planet_id_fkey', 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key('people_vehicle_id_fkey', 'vehicles', ['vehicle_id'], ['id'])
        batch_op.alter_column('persons_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('favorites_id')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_column('vehicle_name')
        batch_op.drop_column('planet_name')
        batch_op.drop_column('persons_name')

    # ### end Alembic commands ###
