"""empty message

Revision ID: 647336d8db7a
Revises: fe526211af7c
Create Date: 2023-09-11 15:14:32.227920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647336d8db7a'
down_revision = 'fe526211af7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_name', sa.String(length=50), nullable=False))
        batch_op.drop_column('persons_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persons_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('people_name')

    # ### end Alembic commands ###
