"""empty message

Revision ID: b77b9bdf4e07
Revises: 4e73a57a5181
Create Date: 2023-09-02 00:40:30.365334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77b9bdf4e07'
down_revision = '4e73a57a5181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_name', sa.String(length=50), nullable=False))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('vehicle_name')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('planet_name')

    # ### end Alembic commands ###
