"""empty message

Revision ID: e0033cc40aeb
Revises: 53fa2138c8c8
Create Date: 2023-09-13 18:30:49.963143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0033cc40aeb'
down_revision = '53fa2138c8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_vehicle_id_fkey', type_='foreignkey')
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('planet_name')
        batch_op.drop_column('vehicle_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planet_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorites_vehicle_id_fkey', 'vehicles', ['vehicle_id'], ['id'])

    # ### end Alembic commands ###
